export interface DevolucionRecibida {
    oficinaRec: string,
    redAfectada: string, 
    oficinaAfectada: string, 
    oficinaEnvio: string, 
    devEspecial: string, 
    tipoProducto: string, 
    productoAfectado: string, 
    tipoCuentaRecuado: string, 
    comprobante: number, 
    chqBanco: string, 
    chqCuenta: string, 
    chqNum: string, 
    chqValor: string, 
    causalDevolucion1: string, 
    causalDevolucion2: string, 
}